const story = [
  {
    title: "La meilleure équipe du monde pendant longtemps",
    desc: "Dix ans après leur fondation, les Globetrotters ont déjà joué plus de 1 000 matchs dans une dizaine d’états des Etats-Unis. Le basket commence peu à peu à se structurer et en 1939 a lieu le premier « World Professional Basketball Tournament », grand tournoi où les meilleures équipes de tout le pays sont conviées à Chicago. Les Globetrotters sont bien évidemment invités mais tombent face aux New York Renaissance, l’une des autres principales équipes noires de l’Amérique de l’entre-deux guerres. Malgré cette déception, les hommes d’Abe Saperstein continuent de dominer la quasi totalité de leurs adversaires avec une facilité déconcertante. Ils commencent alors ce qui fera leur renommée internationale en faisant le show pendant les matchs, humiliant les joueurs adverses par leurs talents de manieurs de ballon. En 1940, il n’y a pas d’accident et les Globetrotters sont couronnés champions du WPBT en dominant les Chicago Bruins en finale par 31 à 29. Alors que plusieurs membres de l’équipe sont envoyés en Europe lors de la Deuxième Guerre mondiale, le groupe continue son parcours et intègre de nouveaux joueurs comme le célèbre Goose Tatum ou Bob Karstens, le premier blanc à intégrer les rangs des Globetrotters. À l’époque, la vie est dure pour les Globetrotters, souvent victimes de discrimination. Ils sont parfois obligés de rouler deux heures après un match pour trouver un hôtel acceptant des clients noirs. Même chose pour les restaurants. Souvent, les joueurs ont du dormir dans leur bus le ventre vide, faute d’avoir trouvé une auberge qui acceptait de les héberger.",
  },
  {
    title: "Meilleurs que les Lakers de George Mikan",
    desc: "À la fin de la guerre, le basket et le sport en général commencent à se structurer et une ligue professionnelle voit le jour aux Etats-Unis : la Basketball Association of America (BAA), qui deviendra deux ans plus tard la National Basketball Association (NBA). Pas impressionné par l’établissement de cette ligue, Abe Saperstein organise en 1948 un match face aux Minneapolis Lakers de George Mikan afin de prouver que son équipe est toujours la meilleure du monde. Devant plus de 17 000 personnes au Chicago Stadium, les Harlem Globetrotters s’imposent par 61 à 59. Rebelotte dès l’année suivante avec une victoire sur le score de 49 à 45 devant cette fois plus de 20 000 personnes. L’année suivante, Nate « Sweetwater » Clifton, membre des Globetrotters, devient le premier joueur noir à rejoindre la NBA pour 25 000 dollars. En 1951 pour célébrer leur 25e anniversaire, les Globetrotters écrasent une sélection composée des meilleurs joueurs universitaires par 55 à 34.",
  },
  {
    title: "La naissance des Washington Generals, loosers perpétuels",
    desc: "L’équipe s’affûble alors d’un « partenaire » de jeu : les Washington Generals. Cette équipe a pour but d’accompagner les Globetrotters partout où ils jouent mais n’a pas le niveau pour lutter et, par la suite, devient partie intégrante du show. Après une défaite en 1962, les Globetrotters enchainent 12 596 (!) victoires pour seulement trois défaites. L’une d’elle intervient en 1971 face aux New York Reds, par 100 à 99 après prolongation. La fin de match a donné lieu à une grande confusion, les arbitres tentant d’arrêter l’horloge mais ne parvenant pas à donner une dernière opportunité de victoire aux Globetrotters. Une autre défaite est intervenue à Vienne en 1995 face à Kareem Abdul-Jabbar et son All-Star Team. Agé de 48 ans, Abdul-Jabbar inscrit 34 points lors de cette rencontre. Cinq ans plus tard, en l’an 2000, les Harlem Globetrotters sont vaincus par Michigan State, alors champion NCAA en titre. La même année, Wilt « The Slit » Chamberlain devient le premier joueur des Globetrotters à avoir son maillot retiré au cours d’une cérémonie au lycée d’Overbrook à Philadelphie.",
  },
  {
    title: "Une marque en déclin mais toujours vivace",
    desc: "Devenu phénomène de société dans les années 1980, les Globetrotters ne sont plus simplement une équipe de basket. En 1982, ils deviennent la première et unique équipe sportive à recevoir leur étoile sur la célèbre « Walk of Fame » à Hollywood. Avec des joueurs comme les Hall of Famer Marques Haynes, Pop Gates, Connie Hawkins, Meadowlark Lemon, Goose Tatum, et surtout Wilt Chamberlain, les Globetrotters sont devenus les symboles du showtime et du sport-spectacle à l’américaine. Ils sont honorés par le monde du basket en 2002 en intégrant le Hall of Fame à Springfield.Aujourd’hui, les Harlem Globetrotters continuent de parcourir le monde, jouant plus de 500 matchs par an sur tous les continents. Si l’équipe est composée de joueurs de second rang dont les talents comiques sont souvent supérieurs à ceux de basketteurs, elle continue d’attirer les foules partout où elle passe. Les Globetrotters ont marqué à jamais l’histoire du basket et ce sport, et plus généralement la société, ne serait pas ce qu’elle est aujourd’hui s’il n’y avait eu le génie du visionnaire qu’était Abe Saperstein. On devrait donc entendre encore longtemps « Sweet Georgia Brown » dans les salles du monde entier…",
  },
];

//export default story;
